services:
  go-app:
    container_name: go-app
    build: .
    environment:
      DATABASE_URL: "user=${POSTGRES_USER} password=${POSTGRES_PASSWORD} host=go_db port=5432 database=${POSTGRES_DB} sslmode=disable"
      SERVER_PORT: ${SERVER_PORT}
    ports:
      - "8080:8080"
    depends_on:
      - go_db
  go_db:
    container_name: go_db
    image: postgres:16.3-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "9898:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: {}
